version: "3"
services:
  web:
    build: .
    ports:
      - 8000:8000 # running on post 8000
    volumes:
      - .:/app # for live reload of the project when code changes
      - application-logs:/app/logs/ # to access log files from outside the container
    networks:
      - my-network # enable connection with redis container
    environment:
      - REDIS_HOST=redis-db # specifiy redis container name
    depends_on:
      - redis-db # wait for redis-db container to be up and running
    
  redis-db:
    image: "redis:7-alpine" # use this image
    volumes:
      - redis-data:/data # to store data persistently
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  application-logs:
  redis-data:

