apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
  labels:
    app: fastapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: rhumbert1/fast-api-docker-example:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-loadbalancer
spec:
  selector:
    app: fastapi
  ports:
  - port: 8000
    targetPort: 8000
  type: LoadBalancer
 